version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"

    target-branch: "develop"

    open-pull-requests-limit: 5

    rebase-strategy: "auto"
    labels:
      - "server"
      - "dependencies"
      - "security"
      
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:*"
        update-types:
          - "minor"
          - "patch"
      aws-sdk:
        patterns:
          - "software.amazon.awssdk:*"
        update-types:
          - "minor"
          - "patch"

      security:
        patterns:
          - "io.jsonwebtoken:*" 
          - "org.springframework.security:*"
        update-types:
          - "patch"

  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"

    target-branch: "develop"

    open-pull-requests-limit: 5

    rebase-strategy: "auto"
    labels:
      - "mobile"
      - "dependencies"
      - "security"

    commit-message:
      prefix: "chore(deps)"
      include: "scope"

    groups:
      expo:
        patterns:
          - "expo"
          - "expo-*"
          - "@expo/*"
        update-types:
          - "minor"
          - "patch"

      react-native:
        patterns:
          - "react-native"
          - "react-native-*"
          - "@react-native-*"
        update-types:
          - "minor"
          - "patch"
          